### ISSUE TITLE
Prepare action caches DLLs unneccesarily

### ISSUE THREAD

**Issue by GuVAnj8Gv3RJ** [GuVAnj8Gv3RJ/NeosAccountDownloader#2]
https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/blob/main/.github/workflows/prepare.yml#L22 should skip downloading the DLLS if the cache exists based on: https://github.com/actions/cache#skipping-steps-based-on-cache-hit

It does not, PRS welcome.

**Comment by Xlinka** [comment]
I think I spotted the issue here. It looks like there's a small syntax glitch in your workflow file that's causing trouble. You're using steps.cache-neos-dlls.cache-hit to check if the cache was hit, but GitHub Actions syntax actually requires you to use steps.<step_id>.outputs.<output_name>.

(This is a guess from documentation and not been tested)

[Context and expression syntax for GitHub Actions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context)

Specifically, it mentions:

To use the output from a previous step, you can use steps.<step_id>.outputs.<output_name>

Also, the output key 'cache-hit' from the GitHub cache action is detailed here:

[actions/cache](https://github.com/actions/cache#outputs)

Which mentions:

cache-hit - A boolean to indicate an exact match was found for the key

Remember that this output will be a string, not a boolean, so your check should be like steps.cache-neos-dlls.outputs['cache-hit'] == 'false'.

**Comment by GuVAnj8Gv3RJ** [comment]
Odd the documentation changed since I last read it. Checking now.

**Comment by GuVAnj8Gv3RJ** [comment]
Fixed: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/commit/f17e2095ab2ee3eabc65de87ece2db7a4d88c39d

thanks
