### ISSUE TITLE
Group missing from downloader

### ISSUE THREAD

**Issue by bontebok** [GuVAnj8Gv3RJ/NeosAccountDownloader#26]
I am in six Neos groups, but only five are seen in the downloader.

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/23562523/eced30e7-624f-4df8-a5fd-f4eed850db5c)

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/23562523/7b26e5f2-ee82-4272-90db-17a2f5b5c8e2)

A scroll bar is show to the right of the group list but moving it only shifts a few pixels vertically and does not display the missing group.

**Comment by stiefeljackal** [comment]
The UI element for groups appears to be very wonky. You can more than likely see all six groups if you mess with the width of the window. I know this to be true because I am in four groups, but I can only see three. If I increase the window width, I see four.

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/14767153-f15a-4d17-9265-bd17d130e4be)

![image](https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/assets/20023996/ecb35e8f-fc5f-4fc0-afcb-51676d6aa058)

I can probably fix this issue and submit a PR for this one.

**Comment by stiefeljackal** [comment]
Fixed it. Will be making a PR soon.

**Comment by stiefeljackal** [comment]
In sorry, @bontebok. @GuVAnj8Gv3RJ  does not want to cooperate with me on this PR and has decided to close it because I was asking for an explanation that the maintainer cannot provide. This is really unfortunate…

**Comment by GuVAnj8Gv3RJ** [comment]
This was resolved in: https://github.com/GuVAnj8Gv3RJ/NeosAccountDownloader/commit/0c40d69e23e5bdd8ce124c5f340ade07369552ec

A new release should be out within the week. Please re-open/make a new issue if you continue to have issues.
