### ISSUE TITLE
Properly identify 7zbson

### ISSUE THREAD

**Issue by GuVAnj8Gv3RJ** [GuVAnj8Gv3RJ/NeosAccountDownloader#83]

**Comment by stiefeljackal** [comment]
From what I had gathered, the best way to identity if the file is 7zbson is to grab it from `assetUri` of the record. That property should have the SHA256 file with the 7zbson extension. If there is a better way to identify a 7zbson with MimeDetective, then I would do that. Otherwise, if you are strapped for time, this will be your best option.
